/** Маппинг жанров пулов → наши группы. */

const GENRE_MAP: Record<string, string> = {
  Pop: "Поп",
  "Dance Pop": "Поп",
  "Synth-Pop": "Поп",
  "Romantic (Lyric)": "Поп",
  House: "Хаус",
  "Tech House": "Хаус",
  "Deep House": "Хаус",
  "Disco House": "Хаус",
  "Melodic House": "Хаус",
  "Future House": "Хаус",
  "Slap House": "Хаус",
  "Bass House": "Хаус",
  "Afro House": "Афро-хаус",
  Amapiano: "Афро-хаус",
  Afrobeats: "Афро-хаус",
  Afro: "Афро-хаус",
  "Hip Hop/Rap": "Хип-хоп/Рэп",
  "Hip-Hop": "Хип-хоп/Рэп",
  HipHop: "Хип-хоп/Рэп",
  Trap: "Хип-хоп/Рэп",
  Rap: "Хип-хоп/Рэп",
  Phonk: "Фонк",
  Rock: "Рок/Метал/Панк",
  "Drum & Bass": "Драм-н-бейс",
  DnB: "Драм-н-бейс",
  Techno: "Техно/Транс",
  Tech: "Техно/Транс",
  Breakbeat: "Бас/Дабстеп",
  Moombahton: "Бас/Дабстеп",
  Dubstep: "Бас/Дабстеп",
  "Jersey Club": "Бас/Дабстеп",
  Bassline: "Бас/Дабстеп",
  "Baile Funk": "Бейл-фанк",
  Rave: "Рейв",
  Disco: "Фанк/Диско",
  "Nu Disco": "Фанк/Диско",
  Funk: "Фанк/Диско",
  "UK Garage": "UK Garage",
  "UK 2 Step": "UK Garage",
  Indie: "Альтернатива/Инди",
  "Indie Dance": "Альтернатива/Инди",
  "Indie Electronic": "Альтернатива/Инди",
  Hyperpop: "Альтернатива/Инди",
  Jazz: "Лаунж/Джаз",
  "R&B": "R&B/Соул",
  RnB: "R&B/Соул",
  "Future Bass": "Электроника",
  Electronic: "Электроника",
  "Mid Tempo": "Электроника",
  Latino: "Дэнс",
  Reggaeton: "Дэнс",
  Dance: "Дэнс",
  Club: "Клубная",
  Mainstage: "EDM",
  "Big Room": "EDM",
  EDM: "EDM",
};

/** Жанр пула → группа (словарь пополняется под шаблонные пулы). */
export function mapGenre(genre: string | null | undefined): string {
  if (!genre) return "Другое";
  return GENRE_MAP[genre] ?? "Другое";
}
